### ISSUE TITLE
look to see if ConfigureMetadata can be faster

### ISSUE THREAD

**Issue by maximilien** [maximilien/bosh-softlayer-cpi#14]
Try to see if there is a way to create the VirtualGuest in POWER_OFF state so that the configure metadata w/o creating VG in active state

**Comment by maximilien** [comment]
I am thinking of closing this since the current Ruby CPI does the same.

\cc @wen-quan and @mattcui to confirm that this is the case. Once you do I will close this. 

Please comment here. Thanks,

@maximilien

**Comment by mattcui** [comment]
@maximilien , discussed with @jianqiu , it's worth looking further at this enhancement, there are a couple of options we could consider to enhance:

1. Specify userData in createObject, don't need to configure metadata subsequently.
2. Set power-off when creating VM, and then configure metadata.

@jianqiu is investigating which option is feasible, will open a feature in PR when we decide to change code.

**Comment by jianqiu** [comment]
@maximilien 
After investigation, option 1 is more feasible. VM metadata could be attached along with creating object, so `ConfigureMetadataOnVirtualGuest` subsequently is no longer needed. I will submit a feature record in Tracker, and PR.

**Comment by maximilien** [comment]
Nice. Thanks @jianqiu
