### ISSUE TITLE
Implement set_vm_metadata

### ISSUE THREAD

**Issue by maximilien** [maximilien/bosh-softlayer-cpi#15]
The set_vm_metadata is used to configure tags and notes to the VM. So need to implement in a way that calls `setObject` on the `VirtualGuest` with tags and notes

**Comment by maximilien** [comment]
After the `softlayer-go` project issue [27](https://github.com/maximilien/softlayer-go/issues/27) is completed make sure to use it here.

**Comment by maximilien** [comment]
OK so `softlayer-go` issue (27)[https://github.com/maximilien/softlayer-go/issues/27] is completed and I can also see where the tags get added to the SL console.

![cursor_and_softlayer_customer_portal____device_list](https://cloud.githubusercontent.com/assets/39187/6423713/ea160ffc-be9e-11e4-8ec8-ec1ffd77219b.png)


Ready to implement.

**Comment by posijon** [comment]
Implemented in PR #34

**Comment by maximilien** [comment]
Looks good. Thx
