### ISSUE TITLE
Some of the eCPI APIs are mismatch with the APIs used in bosh-micro-cli

### ISSUE THREAD

**Issue by xingzhou** [maximilien/bosh-softlayer-cpi#24]
in bosh-micro-cli project, we use string type for the return value of "create_stemcell" and "create_vm", but in current SL eCPI implementation, we just return the int value of stemcell id and vm id, this will lead to bosh-micro-cli runtime error when deploying micro-bosh use SL eCPI.

**Comment by maximilien** [comment]
Hi, @xingzhou,

Can you be specific here. First, see if the latest code is still in error and also please include some of the error you are seeing. Cut and paste the output here.

Thanks,

@maximilien

**Comment by maximilien** [comment]
I am closing this since I believe it is no longer valid. If it is we will see this in our tests.

@xingzhou if you feel otherwise, open a new one.
