### ISSUE TITLE
Using bosh-micro-cli to deploy, the metadata passed to SL VM is not correctly applied

### ISSUE THREAD

**Issue by xingzhou** [maximilien/bosh-softlayer-cpi#25]
We set the static ip for the SL VM in the deployment manifest, but when the VM is launched, the IP of the VM is not the one we set in the deployment manifest.

We tried to deploy a micro-bosh using bosh-micro-cli+SL eCPI, and set the deployment manifest as using manual network+static ips. after the VM launched in SL, we found that the meta.js contains the correct network and ip information, but the openstack/latest/meta_data.json and openstack/content/interfaces file do not contain the correct network information. Therefore, the VM does not have the correct IP address.

This issue will block bosh-micro-cli ping the bosh-agent, because we need to set the bosh-agent vm's IP in the deployment manifest, if the vm does not have the correct IP, the bosh-micro-cli will be timeout when pinging the bosh-agent.

**Comment by maximilien** [comment]
@xingzhou, can you please work with @wen-quan and @gu-bin to make sure they understand this so we can have an appropriate story for this in Tracker (if it's not there already).

Also, please comment here on tracker story ID and anything else you want to add to clarify this.

Thanks,

@maximilien

**Comment by maximilien** [comment]
@wen-quan and @gu-bin,

Do we have appropriate tracker stories for this issue? If yes, then please add links so I can close this once the stories are completed.

Thanks.

**Comment by maximilien** [comment]
I am closing this since @jianqiu has gotten bosh-init to work with the eCPI. 

He's working to finalize the support but I feel that this issue is no longer relevant.

Please reopen if needed.
