### ISSUE TITLE
verify that VMs created have SSH keys of at least 2048 bits long

### ISSUE THREAD

**Issue by maximilien** [maximilien/bosh-softlayer-cpi#26]
This is response to audit checks from SL scans

**Comment by maximilien** [comment]
@mattcui do we have a story for this? I can create one if needed. Thanks.

**Comment by mattcui** [comment]
It's OK, please put the detailed info there and assign the task to @wen-quan

**Comment by maximilien** [comment]
@mattcui done. @wen-quan please take a look at [this tracker story](https://www.pivotaltracker.com/story/show/106497636)
