### ISSUE TITLE
softlayer_stemcell.go deleteVirtualGuestDiskTemplateGroup method is incorrect

### ISSUE THREAD

**Issue by maximilien** [maximilien/bosh-softlayer-cpi#27]
The last part of the method implementation:
```
    deleted, err := vgdtgService.DeleteObject(id)
	if err != nil {
		return bosherr.WrapError(err, "Deleting VirtualGuestBlockDeviceTemplateGroup from service")
	}

	if !deleted {
		return bosherr.WrapError(nil, fmt.Sprintf("Could not delete VirtualGuestBlockDeviceTemplateGroup with id `%d`", id))
	}
```

Does not compile on new `softlayer-go` because, the `DeleteObject` call does not return a bool but rather a transaction. So correct implementation should wait on transaction to complete or fail.

/cc: @posijon

**Comment by posijon** [comment]
Fixed. See PR #33 and Tracker ID [#97439078](https://www.pivotaltracker.com/story/show/97439078).

Paired with @maximilien
