### ISSUE TITLE
Why the "godep store" dont work . It seems some component is missing . 

### ISSUE THREAD

**Issue by dwcnalex** [maximilien/bosh-softlayer-cpi#31]
I git clone the project into my ubuntu vm , and enter the folder . 
Then exec  "godep restore" , it seems some issues as following:
=====================================================
root@alexDevBox:~/go/src/bosh-softlayer-cpi# godep  restore
package github.com/cloudfoundry/bosh-agent/errors
	imports github.com/cloudfoundry/bosh-agent/errors
	imports github.com/cloudfoundry/bosh-agent/errors: cannot find package "github.com/cloudfoundry/bosh-agent/errors" in any of:
	/usr/lib/go/src/pkg/github.com/cloudfoundry/bosh-agent/errors (from $GOROOT)
	/root/go/src/github.com/cloudfoundry/bosh-agent/errors (from $GOPATH)
godep: restore: exit status 1
package github.com/cloudfoundry/bosh-agent/logger
	imports github.com/cloudfoundry/bosh-agent/logger
	imports github.com/cloudfoundry/bosh-agent/logger: cannot find package "github.com/cloudfoundry/bosh-agent/logger" in any of:
	/usr/lib/go/src/pkg/github.com/cloudfoundry/bosh-agent/logger (from $GOROOT)
	/root/go/src/github.com/cloudfoundry/bosh-agent/logger (from $GOPATH)
godep: restore: exit status 1
package github.com/cloudfoundry/bosh-agent/platform/commands
	imports github.com/cloudfoundry/bosh-agent/platform/commands
	imports github.com/cloudfoundry/bosh-agent/platform/commands: cannot find package "github.com/cloudfoundry/bosh-agent/platform/commands" in any of:
	/usr/lib/go/src/pkg/github.com/cloudfoundry/bosh-agent/platform/commands (from $GOROOT)
	/root/go/src/github.com/cloudfoundry/bosh-agent/platform/commands (from $GOPATH)
godep: restore: exit status 1
package github.com/cloudfoundry/bosh-agent/system
	imports github.com/cloudfoundry/bosh-agent/system
	imports github.com/cloudfoundry/bosh-agent/system: cannot find package "github.com/cloudfoundry/bosh-agent/system" in any of:
	/usr/lib/go/src/pkg/github.com/cloudfoundry/bosh-agent/system (from $GOROOT)
	/root/go/src/github.com/cloudfoundry/bosh-agent/system (from $GOPATH)
godep: restore: exit status 1
package github.com/cloudfoundry/bosh-agent/uuid/fakes
	imports github.com/cloudfoundry/bosh-agent/uuid/fakes
	imports github.com/cloudfoundry/bosh-agent/uuid/fakes: cannot find package "github.com/cloudfoundry/bosh-agent/uuid/fakes" in any of:
	/usr/lib/go/src/pkg/github.com/cloudfoundry/bosh-agent/uuid/fakes (from $GOROOT)
	/root/go/src/github.com/cloudfoundry/bosh-agent/uuid/fakes (from $GOPATH)
godep: restore: exit status 1

And when I access these component by my web browser, I got 404 error.
May I get your some suggestion ? Thanks!

**Comment by mattcui** [comment]
Need to update the code to replace all missing packages under github.com/cloudfoundry/bosh-agent/ with github.com/cloudfoundry/bosh-utils/<package_name>

**Comment by maximilien** [comment]
Yes @mattcui, this is indeed a problem.

@posijon and I are working to have a better Godep and scripts (e.g., `bin/build`) that will automatically update dependencies.

If you have other suggestions, please let us know.

**Comment by maximilien** [comment]
@posijon may have fixed this with PR #32. I just merged and next Travis build should confirm.

**Comment by maximilien** [comment]
@posijon just assigned to you. If all works on next Travis build then close it. Thanks all.

**Comment by posijon** [comment]
Fixed dependency links, especially to (bosh-utils)[https://github.com/cloudfoundry/bosh-utils] and updated `Godeps`. As Dr. Max mentioned, see PR #32 
Interestingly, `bosh-agent/internal/...` also has a `bosh-utils`. However, some stuff like logging didn't work immediately, so I stuck with the `cloudfoundry/bosh-utils` link. But it's just something to consider, since we're getting `bosh-agent/internal/...` anyway, if it's usable to decrease the size of our dependencies.
