### ISSUE TITLE
Create has_vm integration test

### ISSUE THREAD

**Issue by posijon** [maximilien/bosh-softlayer-cpi#35]
Also add any required `has_vm` helper methods and test accordingly.
Also look through helper tests to see if any error cases can be added.

These can be found in `test_helpers/*` and also `integration/has_vm/*` after the `has_vm` branch is created.

@maximilien

**Comment by posijon** [comment]
Also see Tracker ID [98155616](https://www.pivotaltracker.com/story/show/98155616)

**Comment by maximilien** [comment]
OK @posijon, closing this since the PRs were merged. Thanks,
@maximilien
