### ISSUE TITLE
About enable/disable OS Reload in eCPI

### ISSUE THREAD

**Issue by mattcui** [maximilien/bosh-softlayer-cpi#60]
@maximilien , I would like to get your advices/comments on this issue. As you know, we need to support OS Reload feature in eCPI to make it work well in Bluemix environment, but I think we should allow the users to choose whether to create a new VM or perform OS reload. So I would like to add a property to enable/disable this feature. I want to place it (osReloadEnabled) in Softlayer section in Micro bosh yaml, then it should be shown at the same place with username/apiKey in config.json:

```json
  "SoftLayer": {
    "username": "cuixuex@cn.ibm.com",
    "apiKey": "fakeKey",
    "osReloadEnabled": true
  }
}
```

In config.go, add it in SoftLayerConfig struct:
```go
type SoftLayerConfig struct {
	Username string `json:"username"`
	ApiKey   string `json:"apiKey"`
	OSReloadEnabled   bool `json:"osReloadEnabled"`
}
```
Then, there needs to add this parameter OSReloadEnabled in every place where to call NewSoftLayerClient. In Create and Delete methods, I will add code at the top to check if it's true or false to determine if performing OS reload or creating a new VM, and just deleting the VM info from sqlite DB or deleting the real VM.

Do you agree with this change, any comment/advice? Thanks.

**Comment by maximilien** [comment]
I like the idea of having this be an optional feature but kind of hate the "pollution" to the Create. Just thinking a bit, could this be done via environment varables and defaulted. So the CPI will have that as option as tou say but defaulted and changed if env variable is set. Just an idea. Thought?

**Comment by mattcui** [comment]
It's a good idea, I think. Let me implement it in alpha release, we could improve in future release if we find a better solution later. So in Create and Delete methods, there will check this environment variable to perform the proper action accordingly. Thanks.

**Comment by maximilien** [comment]
@mattcui cool. I'll look forward to the PRs.

**Comment by maximilien** [comment]
@mattcui, I will close this once the `OsReload` stories are accepted. Thanks.

**Comment by maximilien** [comment]
Closing since OS reload code is already merged.
