### ISSUE TITLE
Unit test failed on stemcell suit

### ISSUE THREAD

**Issue by mattcui** [maximilien/bosh-softlayer-cpi#74]
Unit test failed on stemcell suit, the code in question is https://github.com/mattcui/bosh-softlayer-cpi/blob/os_reload/softlayer/stemcell/softlayer_stemcell_test.go#L54

[1445396531] Disk Suite - 5/5 specs - 7 nodes ••••• SUCCESS! 9.843958ms
[1445396531] Stemcell Suite - 6/6 specs - 7 nodes ••••
------------------------------
• Failure [0.005 seconds]
SoftLayerStemcell #Delete when stemcell does not exist [It] returns error if deleting stemcell does not exist
/Users/mattcui/Developer/go_workspace/src/github.com/maximilien/bosh-softlayer-cpi/softlayer/stemcell/softlayer_stemcell_test.go:55

  Expected an error to have occured.  Got:
      <nil>: nil

  /Users/mattcui/Developer/go_workspace/src/github.com/maximilien/bosh-softlayer-cpi/softlayer/stemcell/softlayer_stemcell_test.go:54
------------------------------
•

Summarizing 1 Failure:

[Fail] SoftLayerStemcell #Delete when stemcell does not exist [It] returns error if deleting stemcell does not exist
/Users/mattcui/Developer/go_workspace/src/github.com/maximilien/bosh-softlayer-cpi/softlayer/stemcell/softlayer_stemcell_test.go:54

Ran 6 of 6 Specs in 0.011 seconds
FAIL! -- 5 Passed | 1 Failed | 0 Pending | 0 Skipped

Ginkgo ran 8 suites in 2.381220512s
Test Suite Failed

**Comment by maximilien** [comment]
@mattcui I think this is fixed.

@karafelix please confirm. Reopen if needed.
